<?php
/**
 * Catálogo centralizado de categorías y tipos de activos.
 * 
 * Para agregar nuevas categorías o tipos en el futuro,
 * solo hay que agregarlos a este arreglo.
 * 
 * Cuando se migre a BD, este archivo se reemplazará por
 * una consulta que devuelva la misma estructura.
 */
return [
    'Equipos de Cómputo' => [
        'Computador de escritorio',
        'Portátil',
        'All in One',
        'Mini PC',
        'Servidor',
        'Chromebook',
        'Tablet',
        'Estación de trabajo',
        'Thin Client',
    ],
    'Periféricos' => [
        'Monitor',
        'Teclado',
        'Mouse',
        'Mouse inalámbrico',
        'Parlantes',
        'Audífonos',
        'Cámara web',
        'Micrófono',
        'Lector de códigos',
        'Lector biométrico',
        'Tableta digitalizadora',
    ],
    'Impresión' => [
        'Impresora láser',
        'Impresora de tinta',
        'Impresora térmica',
        'Multifuncional',
        'Escáner',
        'Fotocopiadora',
        'Plotter',
    ],
    'Redes y Comunicaciones' => [
        'Router',
        'Switch',
        'Access Point',
        'Módem',
        'Rack',
        'Patch Panel',
        'Servidor NAS',
        'Firewall',
        'Antena WiFi',
        'Cable UTP',
        'Patch Cord',
        'Convertidor de fibra',
    ],
    'Equipos Audiovisuales' => [
        'Video Beam',
        'Pantalla de proyección',
        'Smart TV',
        'Televisor',
        'Equipo de sonido',
        'Amplificador',
        'Micrófono inalámbrico',
        'Micrófono de mesa',
        'Cámara',
        'Cámara PTZ',
    ],
    'Mobiliario' => [
        'Escritorio',
        'Mesa rectangular',
        'Mesa redonda',
        'Mesa de laboratorio',
        'Mesa para computador',
        'Silla plástica',
        'Silla universitaria',
        'Silla ergonómica',
        'Silla giratoria',
        'Archivador',
        'Biblioteca',
        'Estante',
        'Gabinete',
        'Armario',
        'Locker',
        'Casillero',
        'Vitrina',
    ],
    'Laboratorio' => [
        'Microscopio',
        'Balanza',
        'Probeta',
        'Tubo de ensayo',
        'Mechero',
        'Fuente de alimentación',
        'Osciloscopio',
        'Multímetro',
        'Generador de funciones',
        'Kit de electrónica',
    ],
    'Eléctricos' => [
        'UPS',
        'Regulador',
        'Estabilizador',
        'Extensión',
        'Multitoma',
        'Planta eléctrica',
        'Inversor',
        'Batería',
    ],
    'Infraestructura' => [
        'Puerta',
        'Ventana',
        'Reja',
        'Aire acondicionado',
        'Ventilador',
        'Cortina',
        'Persianas',
        'Techo',
        'Piso',
        'Lavamanos',
        'Inodoro',
        'Orinal',
    ],
    'Iluminación' => [
        'Lámpara LED',
        'Lámpara fluorescente',
        'Bombillo LED',
        'Reflector',
        'Panel LED',
        'Luminaria de emergencia',
    ],
    'Material Educativo' => [
        'Libro',
        'Diccionario',
        'Atlas',
        'Globo terráqueo',
        'Maqueta',
        'Calculadora científica',
        'Kit didáctico',
        'Material Montessori',
    ],
    'Deportes' => [
        'Balón fútbol',
        'Balón baloncesto',
        'Balón voleibol',
        'Balón microfútbol',
        'Cono',
        'Cronómetro',
        'Colchoneta',
        'Malla',
        'Silbato',
        'Aro',
        'Disco',
        'Jabalina',
    ],
    'Aseo' => [
        'Escoba',
        'Trapero',
        'Balde',
        'Aspiradora',
        'Cepillo',
        'Recogedor',
        'Basurero',
        'Dispensador de jabón',
        'Dispensador de papel',
        'Carro de limpieza',
    ],
    'Seguridad' => [
        'Cámara de seguridad',
        'DVR',
        'NVR',
        'Extintor',
        'Botiquín',
        'Detector de humo',
        'Alarma',
        'Sensor de movimiento',
        'Señal de evacuación',
    ],
    'Cafetería' => [
        'Nevera',
        'Congelador',
        'Estufa',
        'Microondas',
        'Licuadora',
        'Cafetera',
        'Dispensador de agua',
        'Mesa comedor',
        'Silla comedor',
    ],
    'Oficina' => [
        'Archivador',
        'Trituradora de papel',
        'Calculadora',
        'Teléfono fijo',
        'Teléfono IP',
        'Sello',
        'Guillotina',
        'Perforadora',
        'Grapadora',
    ],
    'Señalización' => [
        'Cartelera',
        'Señal de salida',
        'Señal de emergencia',
        'Aviso informativo',
        'Bandera',
        'Astabandera',
        'Placa institucional',
    ],
    'Herramientas y Mantenimiento' => [
        'Taladro',
        'Martillo',
        'Destornillador',
        'Llave inglesa',
        'Caja de herramientas',
        'Escalera',
        'Soldador',
        'Pistola de silicona',
        'Cinta métrica',
    ],
    'Almacenamiento' => [
        'Caja organizadora',
        'Contenedor',
        'Estantería',
        'Canastilla',
        'Gavetero',
        'Bodega móvil',
    ],
    'Otros' => [
        'Reloj',
        'Espejo',
        'Basurero',
        'Pizarra acrílica',
        'Pizarra digital',
        'Corcho',
        'Biombo',
        'Perchero',
        'Decoración institucional',
        'Otro (Especifique)',
    ],
];
