<?php
/**
 * Catálogo de ubicaciones por sede con códigos internos.
 *
 * Cada sede tiene un codigo y un arreglo de ubicaciones,
 * donde cada ubicación tiene {codigo, nombre}.
 *
 * Para agregar ubicaciones en el futuro, solo se edita este archivo.
 * Cuando se migre a BD, se reemplaza por una consulta.
 */
return [
    'Sede Principal' => [
        'codigo' => '01',
        'ubicaciones' => [
            ['codigo' => 'REC',  'nombre' => 'Rectoría'],
            ['codigo' => 'COO',  'nombre' => 'Coordinación'],
            ['codigo' => 'SEC',  'nombre' => 'Secretaría'],
            ['codigo' => 'BIB',  'nombre' => 'Biblioteca'],
            ['codigo' => 'INF1', 'nombre' => 'Aula de Informática 1'],
            ['codigo' => 'INF2', 'nombre' => 'Aula de Informática 2'],
            ['codigo' => 'AUD',  'nombre' => 'Auditorio'],
            ['codigo' => 'ARC',  'nombre' => 'Archivo'],
            ['codigo' => 'BOD',  'nombre' => 'Bodega'],
            ['codigo' => 'RES',  'nombre' => 'Restaurante'],
            ['codigo' => 'CAN',  'nombre' => 'Cancha'],
            ['codigo' => 'PAT',  'nombre' => 'Patio Principal'],
            ['codigo' => 'S001', 'nombre' => 'Salón 01'],
            ['codigo' => 'S002', 'nombre' => 'Salón 02'],
            ['codigo' => 'S003', 'nombre' => 'Salón 03'],
            ['codigo' => 'S004', 'nombre' => 'Salón 04'],
            ['codigo' => 'S005', 'nombre' => 'Salón 05'],
            ['codigo' => 'S006', 'nombre' => 'Salón 06'],
            ['codigo' => 'S007', 'nombre' => 'Salón 07'],
            ['codigo' => 'S008', 'nombre' => 'Salón 08'],
            ['codigo' => 'S009', 'nombre' => 'Salón 09'],
            ['codigo' => 'S010', 'nombre' => 'Salón 10'],
            ['codigo' => 'S011', 'nombre' => 'Salón 11'],
            ['codigo' => 'S012', 'nombre' => 'Salón 12'],
            ['codigo' => 'S013', 'nombre' => 'Salón 13'],
            ['codigo' => 'S014', 'nombre' => 'Salón 14'],
            ['codigo' => 'S015', 'nombre' => 'Salón 15'],
            ['codigo' => 'S016', 'nombre' => 'Salón 16'],
            ['codigo' => 'S017', 'nombre' => 'Salón 17'],
            ['codigo' => 'S018', 'nombre' => 'Salón 18'],
            ['codigo' => 'S019', 'nombre' => 'Salón 19'],
            ['codigo' => 'S020', 'nombre' => 'Salón 20'],
            ['codigo' => 'S021', 'nombre' => 'Salón 21'],
            ['codigo' => 'S022', 'nombre' => 'Salón 22'],
            ['codigo' => 'S023', 'nombre' => 'Salón 23'],
            ['codigo' => 'S024', 'nombre' => 'Salón 24'],
            ['codigo' => 'S025', 'nombre' => 'Salón 25'],
            ['codigo' => 'S026', 'nombre' => 'Salón 26'],
            ['codigo' => 'S027', 'nombre' => 'Salón 27'],
            ['codigo' => 'S028', 'nombre' => 'Salón 28'],
            ['codigo' => 'S029', 'nombre' => 'Salón 29'],
            ['codigo' => 'S030', 'nombre' => 'Salón 30'],
        ],
    ],
    'El Porvenir' => [
        'codigo' => '02',
        'ubicaciones' => [
            ['codigo' => 'COO',  'nombre' => 'Coordinación'],
            ['codigo' => 'BIB',  'nombre' => 'Biblioteca'],
            ['codigo' => 'INF1', 'nombre' => 'Aula de Informática'],
            ['codigo' => 'BOD',  'nombre' => 'Bodega'],
            ['codigo' => 'RES',  'nombre' => 'Restaurante'],
            ['codigo' => 'CAN',  'nombre' => 'Cancha'],
            ['codigo' => 'PAT',  'nombre' => 'Patio'],
            ['codigo' => 'S001', 'nombre' => 'Salón 01'],
            ['codigo' => 'S002', 'nombre' => 'Salón 02'],
            ['codigo' => 'S003', 'nombre' => 'Salón 03'],
            ['codigo' => 'S004', 'nombre' => 'Salón 04'],
            ['codigo' => 'S005', 'nombre' => 'Salón 05'],
            ['codigo' => 'S006', 'nombre' => 'Salón 06'],
            ['codigo' => 'S007', 'nombre' => 'Salón 07'],
            ['codigo' => 'S008', 'nombre' => 'Salón 08'],
            ['codigo' => 'S009', 'nombre' => 'Salón 09'],
            ['codigo' => 'S010', 'nombre' => 'Salón 10'],
            ['codigo' => 'S011', 'nombre' => 'Salón 11'],
            ['codigo' => 'S012', 'nombre' => 'Salón 12'],
            ['codigo' => 'S013', 'nombre' => 'Salón 13'],
            ['codigo' => 'S014', 'nombre' => 'Salón 14'],
            ['codigo' => 'S015', 'nombre' => 'Salón 15'],
            ['codigo' => 'S016', 'nombre' => 'Salón 16'],
            ['codigo' => 'S017', 'nombre' => 'Salón 17'],
            ['codigo' => 'S018', 'nombre' => 'Salón 18'],
            ['codigo' => 'S019', 'nombre' => 'Salón 19'],
            ['codigo' => 'S020', 'nombre' => 'Salón 20'],
        ],
    ],
    'El Progreso' => [
        'codigo' => '03',
        'ubicaciones' => [
            ['codigo' => 'COO', 'nombre' => 'Coordinación'],
            ['codigo' => 'BIB', 'nombre' => 'Biblioteca'],
            ['codigo' => 'BOD', 'nombre' => 'Bodega'],
            ['codigo' => 'CAN', 'nombre' => 'Cancha'],
            ['codigo' => 'PAT', 'nombre' => 'Patio'],
            ['codigo' => 'S001', 'nombre' => 'Salón 01'],
            ['codigo' => 'S002', 'nombre' => 'Salón 02'],
            ['codigo' => 'S003', 'nombre' => 'Salón 03'],
        ],
    ],
    'Los Comodatos' => [
        'codigo' => '04',
        'ubicaciones' => [
            ['codigo' => 'COO', 'nombre' => 'Coordinación'],
            ['codigo' => 'BIB', 'nombre' => 'Biblioteca'],
            ['codigo' => 'INF1', 'nombre' => 'Aula de Informática'],
            ['codigo' => 'BOD', 'nombre' => 'Bodega'],
            ['codigo' => 'RES', 'nombre' => 'Restaurante'],
            ['codigo' => 'PAT', 'nombre' => 'Patio'],
            ['codigo' => 'S001', 'nombre' => 'Salón 01'],
            ['codigo' => 'S002', 'nombre' => 'Salón 02'],
            ['codigo' => 'S003', 'nombre' => 'Salón 03'],
            ['codigo' => 'S004', 'nombre' => 'Salón 04'],
        ],
    ],
    'La Paz' => [
        'codigo' => '05',
        'ubicaciones' => [
            ['codigo' => 'COO', 'nombre' => 'Coordinación'],
            ['codigo' => 'BOD', 'nombre' => 'Bodega'],
            ['codigo' => 'PAT', 'nombre' => 'Patio'],
            ['codigo' => 'RES', 'nombre' => 'Restaurante'],
            ['codigo' => 'S001', 'nombre' => 'Salón 01'],
            ['codigo' => 'S002', 'nombre' => 'Salón 02'],
            ['codigo' => 'S003', 'nombre' => 'Salón 03'],
        ],
    ],
];
